# Generated by Django 3.2.20 on 2023-08-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_discount'),
        ('wishlist', '0002_auto_20230807_1057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='items',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
