# Generated by Django 3.2.20 on 2023-08-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='method',
        ),
    ]
