# Generated by Django 3.2.20 on 2023-08-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='method',
            field=models.TextField(blank=True),
        ),
    ]
