# Generated by Django 3.2.20 on 2023-07-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230712_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dcode', models.CharField(max_length=8)),
                ('expirey_date', models.DateField()),
            ],
        ),
    ]
