# Generated by Django 3.2.20 on 2023-08-10 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='creat_at',
            new_name='create_at',
        ),
    ]
